django_hoc/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from polls import views

urlpatterns = [
    url(r'^$', views.home),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', admin.site.urls),
]

hellodjango/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'hellodjango.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
)

polls/urls.py
from django.conf.urls import url

from polls import views

urlpatterns = [
    # ex: /polls/home/
    url(r'^home$', views.home, name='home'),
    # ex: /polls/instructions/
    url(r'^instructions$', views.instructions, name='instructions'),
    # ex: /polls/install/
    url(r'^install$', views.install, name='install'),
    # ex: /polls/init/
    url(r'^init$', views.init, name='init'),
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    # ex: /polls/all
    url(r'^all$', views.allresults, name='allresults'),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    @classmethod
    def init_questions(cls):
        # Remove all choices and questions
        for question in Question.objects.all():
            for choice in question.choice_set.all():
                choice.delete()
            question.delete()
        question2 = Question.objects.create(question_text="Who is your favorite Star Wars character?",
                                            pub_date=timezone.now())
        for choice_text in ['BB-8', 'C3PO', 'Finn', 'Han Solo', 'Kylo Ren', 'Leia Organa', 'Luke Skywalker', 'R2D2', 'Rey']:
            question2.choice_set.create(choice_text=choice_text, votes=0)
        question1 = Question.objects.create(question_text="What is your favorite cuisine?",
                                            pub_date=timezone.now())
        for choice_text in ['American', 'Chinese', 'Indian', 'Italian', 'Japanese', 'Thai']:
            question1.choice_set.create(choice_text=choice_text, votes=0)
        return True

    def votes(self):
        sum = 0
        for choice in self.choice_set.all():
            sum += choice.votes
        return sum

    def choices_by_vote_count(self):
        return self.choice_set.order_by('-votes')

class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

    def vote_for(self):
        self.votes += 1
        self.save()

polls/views.py
from django.shortcuts import get_object_or_404, get_list_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.utils import timezone

from polls.models import Choice, Question

# Create your views here.

def home(request):
    return render(request, 'polls/home.html')

def instructions(request):
    return render(request, 'polls/instructions.html')

def install(request):
    return render(request, 'polls/install.html')

def init(request):
    Question.init_questions()
    return render(request, 'polls/init.html')

def index(request):
    latest_question_list = Question.objects.filter(
        pub_date__lte=timezone.now()
    ).order_by('-pub_date')[:5]
    return render(request, 'polls/index.html', {'latest_question_list': latest_question_list})

def detail(request, question_id):
    question = get_list_or_404(Question, pk=question_id, pub_date__lte=timezone.now())
    return render(request, 'polls/detail.html', {'question': question[0]})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def allresults(request):
    question_list = Question.objects.filter(
        pub_date__lte=timezone.now()
    ).order_by('-pub_date')
    return render(request, 'polls/allresults.html', {'question_list': question_list})

def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form
        return render(request, 'polls/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.vote_for()
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

polls/templates/polls/allresults.html
<h2>All Poll Questions</h2>

{% if question_list %}
  <ul>
    {% for question in question_list %}
      <li>
        {{ question.question_text }}
        <ul>
          {% for choice in question.choices_by_vote_count %}
            <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
          {% endfor %}
        </ul>
      </li>
    {% endfor %}
  </ul>
{% else %}
  <p>No polls are available.</p>
{% endif %}

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
  {% csrf_token %}
  {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
  {% endfor %}
  <input type="submit" value="Vote" />  
</form>

polls/templates/polls/home.html
<h1>Welcome to the Meadowbrook Hour of Code Python/Django Session!</h1>

<p>To go to the Polls application, click <a href="{% url 'polls:index' %}">here</a></p>

<p>To go to the admin interface, click <a href="/admin">here</a></p>

<p>To see the instructions, click <a href="{% url 'polls:instructions' %}">here</a></p>

<p>To reinitialize database, click <a href="{% url 'polls:init' %}">here</a></p>

polls/templates/polls/index.html
<h1>Meadowbrook Django Hour of Code</h1>

<h2>Poll Questions</h2>

{% if latest_question_list %}
  <ul>
    {% for question in latest_question_list %}
      <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a> ({{ question.votes }} votes)</li>
    {% endfor %}
  </ul>
  <a href="{% url 'polls:allresults' %}">see all results</a>
{% else %}
  <p>No polls are available.</p>
{% endif %}

<a href="{% url 'polls:home' %}">Return to home page</a>

polls/templates/polls/init.html
<h1>Database reinitialied</h1>

<a href="{% url 'polls:home' %}">Return to home page</a>

polls/templates/polls/install.html
<a href="/">Return to Home page</a>&nbsp;&nbsp;
<a href="{% url 'polls:instructions' %}">Return to Instructions</a>

<h1>Installation Instructions</h1>

<ol>
  <li>If you are using a Mac, you will need to install the XCode command-line tools (which includes <i>git</i>) using the command: <i>xcode-select --install</i></li>
  <li>Install VirtualBox 5.0. You can download it here: <a href="https://www.virtualbox.org/wiki/Download_Old_Builds_5_0">VirtualBox 5.0 Download Page</a></li>
  <li>Install Vagrant. You can download it here: <a href="https://www.vagrantup.com/downloads.html">Vagrant Download Page</a></li>
  <li>Download the vagrant box django_hoc_trusty64.box from here (warning: it is over 500MB!): <a href="https://dl.dropboxusercontent.com/u/69933626/django_hoc_trusty64.box">django_hoc_trusty64.box</a></li>
  <li>Import the vagrant box for django_hoc into vagrant: <i>vagrant box add django_hoc ~/Downloads/django_hoc_trusty64.box</i></li>
  <li>Clone the github repository into a new directory called <b>django</b>: <i>git clone https://github.com/glendudek/django_hoc.git django</i></li>
  <li>Add the heroku app remote (you should be assigned a unique two-digit number to put in place of ##, or use 99 for one that may shared*): <i>cd django; git remote add heroku git@heroku.com:django-hoc-##.git</i></li>

 <br/>*If you are using a shared heroku app like django-hoc-99, you may need to use the --force flag on git push to overwrite someone else's changes, e.g. <i>git push --force heroku master</i>
</ol>

<h2>Reinitializing a computer for a new student</h2>

<ol>
  <li>From a terminal window, change to the django directory: <i>cd django</i></li>
  <li>Shutdown and restart vagrant: <i>vagrant halt; vagrant up</i>
  <li>SSH into the vagrant instance: <i>vagrant ssh</i>
  <li>Restore the original code: <i>git fetch; git reset --hard origin/master</i></li>
  <li>Push the initial code to heroku: <i>git push --force heroku origin/init:master</i></li>
  <li>Reinitialize the local database:
    <ul>
      <li>start the local application: <i>./runserver</i></li>
      <li>use a local browser to bring up the home page at localhost:8000</li>
      <li>click on the link to reinitialize the database</li>
    </ul>
  </li>
  <li>Reinitialize the database at heroku:</li>
    <ul>
      <li>use a browser to bring up the home page at <i>http://django-hoc-##.herokuapp.com</i>, where <i>##</i> is the assigned number of the computer</li>
      <li>click on the link to reinitialize the database</li>
    </ul>
  </li>
</ol>

<ol>
<a href="/">Return to Home page</a>&nbsp;&nbsp;
<a href="{% url 'polls:instructions' %}">Return to Instructions</a>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
  {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
  {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>, or

<a href="{% url 'polls:index' %}">Select another question</a>